name: MishkaInstaller CI

on:
  push:
    branches:
      - refactor-dependencies
  pull_request:
    branches:
      - refactor-dependencies

jobs:
  ci:
    env:
      GITHUB_ACTION: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.17.1"
              otp: "27.0"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Elixir and Erlang Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Source Compiling
        run: |
          mix deps.get
          mix deps.compile

      - name: Set up environment
        run: |
          echo "PROJECT_PATH=$(pwd)" >> $GITHUB_ENV
          mkdir -p $(pwd)/deployment/test/extensions

      - name: Run test with temporary information
        run: |
          mix test --trace
        env:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
